# Maintainer: Yann Jorelle <yann@yannjorelle.com>
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=kingler-bin
pkgver=0.2.0
pkgrel=1
pkgdesc="Print pokemon sprites in your terminal"
url="https://github.com/yannjor/kingler"
license=("GPL-3.0")
arch=("x86_64")
provides=("kingler")
conflicts=("kingler")
source=("https://github.com/yannjor/kingler/releases/download/v$pkgver/kingler-$pkgver-x86_64.tar.gz")
sha256sums=("c06872d5c0c9e143768a2eccda8baaf956c532e98f131b8e1a7d3caeb4142001")

package() {
    install -Dm755 kingler -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
